### ISSUE TITLE
get [error: json: unknown field “metadata” ] error when following google cloud otlp pipeline installation

### ISSUE THREAD

**Issue by wabrit** [GoogleCloudPlatform/otlp-k8s-ingest#20]
### Environment

```
Google Cloud SDK 490.0.0
beta 2024.08.23
bq 2.1.8
core 2024.08.23
gsutil 5.30

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.7-gke.1104000", GitCommit:"c6376e612cc2ff3f24b8d87f73c937d52416c0fa", GitTreeState:"clean", BuildDate:"2024-07-22T09:17:29Z", GoVersion:"go1.22.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

### Scenario
Following the instructions for [installing the Google Cloud OTLP pipeline](https://cloud.google.com/blog/products/devops-sre/new-curated-opentelemetry-ingestion-pipeline-for-gke).

The instructions specify the following call to kubectl, which should result in the creation of the various kubernetes resources required by the OLTP pipeline:

```
kubectl kustomize https://github.com/GoogleCloudPlatform/otlp-k8s-ingest/k8s/base | envsubst | kubectl apply -f -
```

However, rather than the expected resource creations, the error `Error: json: unknown field "metadata"` is reported without any further diagnostic information. Adding various levels of --v=<level> to kubectl doesn't provide any further info.

### Additional Info

I git cloned that repo and removed the `metadata.name` field from the `kustomization.yaml` file, and the problem went away.

Also it appears not to be an issue with e.g. Gcloud SDK 458.0.1.

**Comment by damemi** [comment]
Hi, I don't see this error when running with the following:
```
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3-gke.1969001

$ gcloud version
Google Cloud SDK 495.0.0
alpha 2024.09.27
beta 2024.09.27
bq 2.1.8
bundled-python3-unix 3.11.9
cloud-run-proxy 0.5.0
core 2024.09.27
enterprise-certificate-proxy 0.3.3
gcloud-crc32c 1.0.0
gke-gcloud-auth-plugin 0.5.9
gsutil 5.30
```

Regardless, I opened https://github.com/GoogleCloudPlatform/otlp-k8s-ingest/pull/22 to remove the `metadata.name` field as it doesn't seem to be required. But @wabrit I am curious if you can try with a more recent client if the current approach works

**Comment by wabrit** [comment]
Hi @damemi - thanks very much for making this change; I'm going to be OOF for a while but when I get back I will try and repro with the latest SDK to see if it is an issue.
