### ISSUE TITLE
HPA configuration not included in base

### ISSUE THREAD

**Issue by olepbr** [GoogleCloudPlatform/otlp-k8s-ingest#25]
Hi!

#18 did not update `k8s/base/kustomization.yml` to include `k8s/base/5_hpa.yaml` in the list of resources, and as a result the HPA configuration is not included by default; is that intentional or an oversight?

Many thanks,
Ole

**Comment by dashpole** [comment]
Thanks for finding and reporting this!  It is definitely an oversight.
